#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("test.Resource", IsApplication=true)]

namespace test
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int all_receipts_info_320 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_dialog = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_dialog_title = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cloud_services_logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dashboard = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int deviceId = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int deviceIdTitle = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int deviceName = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int deviceNameTitle = 2131099655;
			
			// aapt resource value: 0x7f060010
			public const int myButton = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int myLayout = 2131099663;
			
			// aapt resource value: 0x7f060004
			public const int passwordEditText = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int registButton = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int retailerName = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int retailerNameTitle = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int showCloudServicePageButton = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int showWebDashboardButton = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int textView3 = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int textView4 = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int textView5 = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int title = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int userNameEditText = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int dialog_setting = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050013
			public const int app_name = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int common_dialog_id = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int connection_server_authority = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int current_setting = 2131034134;
			
			// aapt resource value: 0x7f05001f
			public const int hello = 2131034143;
			
			// aapt resource value: 0x7f050000
			public const int hint_password = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int hint_username = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int label_device_id = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int label_device_name = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int label_learn = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int label_password = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int label_retailer_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int label_username = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int login_server_authority = 2131034135;
			
			// aapt resource value: 0x7f050008
			public const int message_invalid_login_data = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int message_login_success = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int message_try_again = 2131034122;
			
			// aapt resource value: 0x7f050018
			public const int no_data = 2131034136;
			
			// aapt resource value: 0x7f05000b
			public const int register = 2131034123;
			
			// aapt resource value: 0x7f050019
			public const int returned_error_id = 2131034137;
			
			// aapt resource value: 0x7f05000c
			public const int title_complete = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int title_complete_update_information = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int title_failed_to_communicate_service = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int title_failed_to_login = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int title_login_success = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int title_star_cloud_service = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int toast_input_password = 2131034130;
			
			// aapt resource value: 0x7f05001a
			public const int unexpected_response_code_id = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int update_status_server_path = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int upload_bitmap_server_path = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int upload_data_server_path = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int welcome_url = 2131034142;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
